-- =====================================================================
-- DGP · Torre de Control Logística — MVP
-- Esquema para Supabase (plan Free) · Postgres 15/17 · sin extensiones de pago
-- Pegar completo en SQL Editor → Run. Idempotente (se puede volver a ejecutar).
-- ATENCIÓN: las políticas RLS de este archivo permiten acceso total con la
-- clave anon. Es deliberado para la DEMO. En producción se sustituyen por
-- políticas por rol (ver propuesta técnica, sección 16).
-- =====================================================================
create extension if not exists pgcrypto;

create table if not exists bodegas (
  id uuid primary key default gen_random_uuid(),
  codigo text unique not null, nombre text not null, direccion text,
  lat double precision, lng double precision, hora_corte text default '15:00'
);
create table if not exists zonas (
  id uuid primary key default gen_random_uuid(),
  codigo text unique not null, nombre text not null, color text, prioridad int default 3
);
create table if not exists clientes (
  id uuid primary key default gen_random_uuid(),
  codigo text unique not null, nombre text not null, zona_codigo text references zonas(codigo),
  direccion text, lat double precision, lng double precision,
  geo_estado text default 'pendiente',          -- pendiente|automatica|validada|dudosa|aproximada
  ventana_inicio text, ventana_fin text, tiempo_servicio_min int default 15,
  contacto text, telefono text, ejecutivo text,
  credito_bloqueado boolean default false, zoho_account_id text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists articulos (
  id uuid primary key default gen_random_uuid(),
  sku text unique not null, nombre text not null, categoria text, precio numeric(10,2),
  peso_kg numeric(10,3), volumen_m3 numeric(10,4), unidades_por_caja int, fragil boolean default false,
  ubicacion text, codigo_barras text, zoho_item_id text
);
create table if not exists vehiculos (
  id uuid primary key default gen_random_uuid(),
  placa text unique not null, nombre text, tipo text,
  cap_valor numeric(12,2) default 2500, cap_peso_kg numeric(10,2), cap_volumen_m3 numeric(10,3), cap_cajas int, cap_posiciones int,
  km_por_litro numeric(6,2), panapass_tag text, conductor text, ayudante text, color text, costo_km numeric(8,3),
  odometro_km numeric(12,1), activo boolean default true
);
create table if not exists personas (
  id uuid primary key default gen_random_uuid(),
  nombre text not null, rol text not null, telefono text, pin text, activo boolean default true,
  unique (nombre, rol)
);
create table if not exists reglas (
  id uuid primary key default gen_random_uuid(),
  clave text unique not null, valor jsonb not null, descripcion text, accion text,
  actualizado_por text, updated_at timestamptz default now()
);
create table if not exists pedidos (
  id uuid primary key default gen_random_uuid(),
  numero_so text unique not null, numero_factura text, cliente_id uuid references clientes(id),
  fecha date default current_date, prioridad int default 3,
  valor numeric(12,2) not null, peso_kg numeric(10,2), volumen_m3 numeric(10,4), cajas int,
  estado text default 'pendiente_validar',   -- pendiente_validar|elegible|en_excepcion|planificado|pendiente_autorizacion|diferido|entregado|parcial|no_entregado|cancelado
  causa text, grupo text, ruta_id uuid, secuencia int, zoho_salesorder_id text,
  autorizado_por text, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists pedido_lineas (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid references pedidos(id) on delete cascade, sku text references articulos(sku),
  cantidad_cajas int not null, precio numeric(10,2), entregado int
);
create table if not exists rutas (
  id uuid primary key default gen_random_uuid(),
  codigo text not null, fecha date default current_date, vehiculo_id uuid references vehiculos(id),
  conductor text, ayudante text, zona_codigo text,
  estado text default 'simulada',  -- simulada|aprobada|publicada|en_cargue|liberada|en_ruta|cerrada|conciliada
  version int default 1, valor numeric(12,2) default 0, peso_kg numeric(10,2) default 0, volumen_m3 numeric(10,4) default 0, cajas int default 0, posiciones numeric(6,1) default 0,
  km_plan numeric(8,1), km_real numeric(8,1), hora_salida text, hora_fin_prevista text, limite text,
  geometria jsonb,                 -- polilínea OSRM [[lat,lng],...]
  salida_at timestamptz, llegada_at timestamptz, odometro_salida numeric(12,1), odometro_llegada numeric(12,1),
  created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table pedidos drop constraint if exists pedidos_ruta_fk;
alter table pedidos add constraint pedidos_ruta_fk foreign key (ruta_id) references rutas(id) on delete set null;
create table if not exists paradas (
  id uuid primary key default gen_random_uuid(),
  ruta_id uuid references rutas(id) on delete cascade, secuencia int not null,
  tipo text default 'entrega',     -- entrega|compra|almuerzo|recogida|combustible
  pedido_id uuid references pedidos(id), cliente_id uuid references clientes(id),
  lat double precision, lng double precision, eta text, ventana_inicio text, ventana_fin text, duracion_min int, km_tramo numeric(8,2),
  estado text default 'pendiente', -- pendiente|en_sitio|atendida|parcial|no_entregada|reprogramada
  resultado text, receptor text, firma text, foto text, notas text,
  checkin_at timestamptz, checkout_at timestamptz, checkin_lat double precision, checkin_lng double precision, distancia_checkin_m numeric(8,1)
);
create table if not exists manifiestos (
  id uuid primary key default gen_random_uuid(),
  ruta_id uuid unique references rutas(id) on delete cascade, numero text, estado text default 'pendiente',
  preparador text, cargador text, verificador text, inicio_cargue timestamptz, fin_cargue timestamptz
);
create table if not exists manifiesto_lineas (
  id uuid primary key default gen_random_uuid(),
  manifiesto_id uuid references manifiestos(id) on delete cascade, sku text, ubicacion text, requerido int, cargado int default 0
);
create table if not exists eventos (
  id uuid primary key default gen_random_uuid(),
  ruta_id uuid references rutas(id) on delete cascade, parada_id uuid references paradas(id) on delete cascade,
  tipo text not null, detalle jsonb, lat double precision, lng double precision,
  ts_dispositivo timestamptz, offline boolean default false, actor text, created_at timestamptz default now()
);
create table if not exists incidencias (
  id uuid primary key default gen_random_uuid(),
  ruta_id uuid references rutas(id) on delete cascade, parada_id uuid, tipo text, descripcion text, demora_min int,
  estado text default 'registrada', actor text, created_at timestamptz default now(), cerrada_at timestamptz
);
create table if not exists alertas (
  id uuid primary key default gen_random_uuid(),
  tipo text, severidad text default 'media', titulo text, detalle text, entidad text, destinatario text,
  leida boolean default false, cerrada boolean default false, created_at timestamptz default now()
);
create table if not exists auditoria (
  id bigint generated always as identity primary key,
  entidad text, entidad_id text, accion text, detalle text, valor_anterior jsonb, valor_nuevo jsonb,
  actor text, automatico boolean default false, created_at timestamptz default now()
);
create table if not exists abastecimientos (
  id uuid primary key default gen_random_uuid(),
  ruta_id uuid references rutas(id) on delete cascade, vehiculo_id uuid references vehiculos(id), fecha timestamptz default now(),
  estacion text, litros numeric(8,2), costo numeric(10,2), odometro_km numeric(12,1), foto text
);
create table if not exists peajes (
  id uuid primary key default gen_random_uuid(),
  ruta_id uuid references rutas(id) on delete cascade, punto text, monto_estimado numeric(8,2), monto_real numeric(8,2),
  fuente text default 'estimado', fuera_de_ruta boolean default false, conciliado boolean default false
);
create table if not exists costos_ruta (
  ruta_id uuid primary key references rutas(id) on delete cascade,
  km_plan numeric(8,1), km_real numeric(8,1), litros_esperados numeric(8,2), litros_reales numeric(8,2), desviacion_pct numeric(6,1),
  costo_combustible numeric(10,2), costo_peajes numeric(10,2), costo_mano_obra numeric(10,2), costo_mantenimiento numeric(10,2),
  costo_total numeric(12,2), valor_vendido numeric(12,2), entregas int, costo_por_entrega numeric(10,2), costo_por_km numeric(10,3), pct_sobre_venta numeric(6,2),
  calculado_at timestamptz default now()
);
create table if not exists posiciones (
  id bigint generated always as identity primary key,
  ruta_id uuid references rutas(id) on delete cascade, lat double precision, lng double precision, velocidad numeric(5,1), ts timestamptz default now()
);

create index if not exists ix_pedidos_estado on pedidos(fecha, estado);
create index if not exists ix_paradas_ruta on paradas(ruta_id, secuencia);
create index if not exists ix_eventos_ruta on eventos(ruta_id, created_at);
create index if not exists ix_auditoria on auditoria(created_at desc);

-- Vistas útiles para tableros
create or replace view v_torre as
select r.id, r.codigo, r.fecha, r.estado, r.version, v.placa, r.conductor, r.valor, r.km_plan, r.km_real,
  (select count(*) from paradas p where p.ruta_id=r.id and p.tipo='entrega') as entregas,
  (select count(*) from paradas p where p.ruta_id=r.id and p.estado='atendida') as atendidas,
  (select count(*) from paradas p where p.ruta_id=r.id and p.estado in ('parcial','no_entregada')) as novedades
from rutas r left join vehiculos v on v.id=r.vehiculo_id;

-- RLS DEMO: acceso total con clave anon (¡solo demo!)
do $$ declare t text; begin
  foreach t in array array['bodegas','zonas','clientes','articulos','vehiculos','personas','reglas','pedidos','pedido_lineas','rutas','paradas','manifiestos','manifiesto_lineas','eventos','incidencias','alertas','auditoria','abastecimientos','peajes','costos_ruta','posiciones'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists demo_all on %I', t);
    execute format('create policy demo_all on %I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- Realtime para la torre de control (posiciones y paradas en vivo)
do $$ begin
  begin alter publication supabase_realtime add table paradas; exception when others then null; end;
  begin alter publication supabase_realtime add table eventos; exception when others then null; end;
  begin alter publication supabase_realtime add table posiciones; exception when others then null; end;
  begin alter publication supabase_realtime add table rutas; exception when others then null; end;
end $$;


-- ===== DATOS SEMILLA (empresas de Panamá como clientes de demostración; coordenadas de OpenStreetMap, marcadas para validar) =====
-- Borra los datos operativos previos y recarga maestros y pedidos del día.
truncate eventos, incidencias, alertas, auditoria, abastecimientos, peajes, costos_ruta, posiciones, manifiesto_lineas, manifiestos, paradas, pedido_lineas, pedidos, rutas restart identity cascade;
insert into bodegas(codigo,nombre,direccion,lat,lng,hora_corte) values ('VA','Bodega Vista Alegre','Vista Alegre, Arraiján, Panamá Oeste',8.956,-79.672,'15:00') on conflict (codigo) do update set nombre=excluded.nombre, lat=excluded.lat, lng=excluded.lng;
insert into zonas(codigo,nombre,color,prioridad) values ('CENTRO','Centro · Bella Vista · San Francisco','#2563EB',1) on conflict (codigo) do update set nombre=excluded.nombre,color=excluded.color;
insert into zonas(codigo,nombre,color,prioridad) values ('ESTE','Costa del Este · Juan Díaz · Tocumen','#0D9488',2) on conflict (codigo) do update set nombre=excluded.nombre,color=excluded.color;
insert into zonas(codigo,nombre,color,prioridad) values ('NORTE','24 de Diciembre · Las Cumbres','#D97706',3) on conflict (codigo) do update set nombre=excluded.nombre,color=excluded.color;
insert into zonas(codigo,nombre,color,prioridad) values ('OESTE','Arraiján · La Chorrera','#7C3AED',2) on conflict (codigo) do update set nombre=excluded.nombre,color=excluded.color;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C001','Supermercados El Rey · Vía España','CENTRO','Supermercado El Rey Vía España Panamá',8.9875,-79.5247,'aproximada',null,null,25,'Recepción / Almacén','+507 6431-3471','Gabriel Ruiz',false,'zcrm_4870001') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C002','Riba Smith · Bella Vista','CENTRO','Riba Smith, Avenida Simón Bolívar, Urbanización Herbruger, El Carmen, Bella Vista, Distrito de Panamá, Provincia de Panamá, 0801, Panamá',8.998534,-79.525343,'automatica','08:00','10:00',25,'Recepción / Almacén','+507 6504-1791','Gabriel Ruiz',false,'zcrm_4870002') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C003','Farmacias Arrocha · Vía Argentina','CENTRO','Farmacias Arrocha, Avenida Argentina, El Cangrejo, Bella Vista, Distrito de Panamá, Provincia de Panamá, 0807, Panamá',8.988177,-79.528687,'automatica',null,null,15,'Recepción / Almacén','+507 6174-9779','Sofía Lam',false,'zcrm_4870003') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C004','Hotel El Panamá','CENTRO','Hotel El Panamá Vía España',8.986,-79.524,'aproximada','09:00','10:00',20,'Recepción / Almacén','+507 6196-6991','Gabriel Ruiz',false,'zcrm_4870004') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C005','Pacífica Salud · Hospital Punta Pacífica','CENTRO','Hospital Punta Pacífica, Boulevard Pacífica, Punta Pacífica, San Francisco, Distrito de Panamá, Provincia de Panamá, 0816, Panamá',8.981984,-79.510273,'automatica','08:00','12:00',30,'Recepción / Almacén','+507 6696-1950','Sofía Lam',false,'zcrm_4870005') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C006','Clínica Hospital San Fernando','CENTRO','Clínica Hospital San Fernando, Calle 79 Oeste, La Loma, Pueblo Nuevo, Distrito de Panamá, Provincia de Panamá, 0801, Panamá',9.003638,-79.516689,'automatica','08:00','11:00',30,'Recepción / Almacén','+507 6619-4517','Sofía Lam',false,'zcrm_4870006') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C007','Hotel Riu Plaza Panamá','CENTRO','Hotel Riu Plaza Panama, Calle 50 D Este, Marbella, Bella Vista, Distrito de Panamá, Provincia de Panamá, 7581, Panamá',8.981111,-79.521017,'automatica',null,null,20,'Recepción / Almacén','+507 6138-2408','Gabriel Ruiz',false,'zcrm_4870007') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C008','Restaurante Tinajas','CENTRO','Tinajas, 22, Calle 51 Este, Marbella, Bella Vista, Distrito de Panamá, Provincia de Panamá, 0807, Panamá',8.979555,-79.52691,'automatica',null,null,15,'Recepción / Almacén','+507 6544-7851','Sofía Lam',false,'zcrm_4870008') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C009','Multiplaza Pacific Mall · Administración','CENTRO','Multiplaza Pacific Mall Panamá',8.98,-79.51,'aproximada','13:00','16:00',20,'Recepción / Almacén','+507 6171-4943','Gabriel Ruiz',false,'zcrm_4870009') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C010','Niko''s Café · Calle 50','CENTRO','Niko''s Café Calle 50 Panamá',8.984,-79.518,'aproximada',null,null,10,'Recepción / Almacén','+507 6192-7955','Sofía Lam',false,'zcrm_4870010') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C011','Colegio Javier','CENTRO','Colegio Javier, Ancón, Distrito de Panamá, Provincia de Panamá, 0818, Panamá',9.004385,-79.560305,'automatica','07:30','09:00',20,'Recepción / Almacén','+507 6160-3028','Gabriel Ruiz',false,'zcrm_4870011') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C012','Universidad de Panamá · Campus Central','CENTRO','Universidad de Panamá campus central',8.984,-79.532,'aproximada','08:00','12:00',25,'Recepción / Almacén','+507 6328-2013','Sofía Lam',false,'zcrm_4870012') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C013','Súper 99 · Calidonia','CENTRO','Super 99, Avenida Central, Calidonia, Panamá, Calidonia, Distrito de Panamá, Provincia de Panamá, 0843, Panamá',8.966356,-79.540194,'automatica',null,null,25,'Recepción / Almacén','+507 6690-7499','Gabriel Ruiz',false,'zcrm_4870013') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C014','Supermercados Xtra · Juan Díaz','ESTE','Xtra, Avenida José Agustín Arango, El Laurel Villa Venus, San Pedro, Juan Díaz, Distrito de Panamá, Provincia de Panamá, Panamá',9.044215,-79.451186,'automatica',null,null,25,'Recepción / Almacén','+507 6150-4622','Gabriel Ruiz',false,'zcrm_4870014') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C015','Novey · Los Pueblos','ESTE','Novey Los Pueblos Panamá',9.04,-79.44,'aproximada',null,null,15,'Recepción / Almacén','+507 6147-3181','Sofía Lam',true,'zcrm_4870015') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C016','Do It Center · Costa del Este','ESTE','Do It Center Costa del Este',9.01,-79.47,'aproximada','08:00','10:00',20,'Recepción / Almacén','+507 6396-7867','Gabriel Ruiz',false,'zcrm_4870016') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C017','Riba Smith · Costa del Este','ESTE','Riba Smith, Avenida Marina Norte, Costa del Este, Campo Lindbergh, Juan Díaz, Distrito de Panamá, Provincia de Panamá, Panamá',9.023703,-79.462354,'automatica',null,null,25,'Recepción / Almacén','+507 6247-9858','Sofía Lam',false,'zcrm_4870017') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C018','PowerClub · Costa del Este','ESTE','PowerClub Costa del Este',9.0085,-79.475,'aproximada',null,null,15,'Recepción / Almacén','+507 6220-6054','Gabriel Ruiz',false,'zcrm_4870018') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C019','Súper 99 · Villa Lucre','ESTE','Super 99, Avenida Rafael E. Alemán, Villa Lucre, José Domingo Espinar, San Miguelito, Panamá, Provincia de Panamá, 0801, Panamá',9.04152,-79.478384,'dudosa',null,null,25,'Recepción / Almacén','+507 6673-3961','Sofía Lam',false,'zcrm_4870019') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C020','Pío Pío · Juan Díaz','ESTE','Pio Pio, Calle 114 Este, Campo Lindbergh, Juan Díaz, Distrito de Panamá, Provincia de Panamá, 0801, Panamá',9.031695,-79.474223,'automatica',null,null,15,'Recepción / Almacén','+507 6205-4078','Gabriel Ruiz',false,'zcrm_4870020') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C021','Metromall · Administración','ESTE','Metromall, Avenida Domingo Díaz, Rufina Alfaro, San Miguelito, Panamá, San Antonio, Provincia de Panamá, Panamá',9.052629,-79.451665,'automatica','13:00','16:00',20,'Recepción / Almacén','+507 6481-2596','Sofía Lam',false,'zcrm_4870021') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C022','Felipe Motta · Costa del Este','ESTE','Felipe Motta Costa del Este',9.012,-79.465,'aproximada',null,null,15,'Recepción / Almacén','+507 6660-2028','Gabriel Ruiz',false,'zcrm_4870022') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C023','Crowne Plaza Aeropuerto Tocumen','NORTE','Crowne Plaza, Avenida Domingo Díaz, Tocumen, Distrito de Panamá, Provincia de Panamá, Panamá',9.069931,-79.394037,'automatica',null,null,20,'Recepción / Almacén','+507 6677-1976','Gabriel Ruiz',false,'zcrm_4870023') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C024','Súper 99 · Tocumen','NORTE','Super 99, Carretera Panamericana, Sector 3, Tocumen, Distrito de Panamá, Provincia de Panamá, Panamá',9.103738,-79.369163,'automatica',null,null,25,'Recepción / Almacén','+507 6733-4374','Sofía Lam',false,'zcrm_4870024') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C025','Centro Comercial Los Andes · Administración','NORTE','Centro Comercial Los Andes N°1, Vía Principal Los Andes N°1 y La Nueve de Enero, Los Andes N° 1, Amelia Denis de Icaza, San Miguelito, Panam',9.040851,-79.508946,'automatica',null,null,20,'Recepción / Almacén','+507 6608-9711','Gabriel Ruiz',false,'zcrm_4870025') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C026','El Machetazo · 24 de Diciembre','NORTE','El Machetazo, Carretera Panamericana, Megamall, Pradera Azul, 24 de Diciembre, Distrito de Panamá, Provincia de Panamá, Panamá',9.100957,-79.355543,'automatica','07:00','10:00',25,'Recepción / Almacén','+507 6537-6146','Sofía Lam',false,'zcrm_4870026') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C027','Farmacias Metro · Las Cumbres','NORTE','Farmacias Metro Las Cumbres Panamá',9.105,-79.525,'aproximada',null,null,10,'Recepción / Almacén','+507 6576-8424','Gabriel Ruiz',false,'zcrm_4870027') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C028','Cochez · Tocumen','NORTE','Cochez | Tocumen, Avenida Domingo Díaz, Las Mañanitas, Distrito de Panamá, Provincia de Panamá, Panamá',9.068808,-79.40887,'automatica',null,null,15,'Recepción / Almacén','+507 6470-5911','Sofía Lam',false,'zcrm_4870028') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C029','El Machetazo · Arraiján','OESTE','El Machetazo, Avenida Hato Montaña, Villa Diana, Nuevo Arraiján, Arraiján, Panamá Oeste, 1015, Panamá',8.916153,-79.743386,'automatica',null,null,25,'Recepción / Almacén','+507 6354-3945','Gabriel Ruiz',false,'zcrm_4870029') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C030','Westland Mall · Administración','OESTE','Westland Mall, Nuevo Arraiján, Arraiján, Panamá Oeste, Panamá',8.921816,-79.705276,'automatica','10:00','12:00',20,'Recepción / Almacén','+507 6815-4999','Sofía Lam',false,'zcrm_4870030') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C031','Súper 99 · La Chorrera','OESTE','Super 99, Calle 42 Norte, El Coco, La Chorrera, Panamá Oeste, 1015, Panamá',8.873887,-79.795199,'automatica',null,null,25,'Recepción / Almacén','+507 6183-5919','Gabriel Ruiz',false,'zcrm_4870031') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C032','Farmacias Arrocha · La Chorrera','OESTE','Arrocha, Boulevard Costa Verde, La Chorrera, Panamá Oeste, 1015, Panamá',8.893925,-79.751102,'automatica',null,null,15,'Recepción / Almacén','+507 6637-9111','Sofía Lam',false,'zcrm_4870032') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C033','Novey · Arraiján','OESTE','Novey, Avenida Hendrikson, Panamá Pacífico, Veracruz, Arraiján, Panamá Oeste, Panamá',8.917863,-79.593413,'automatica',null,null,15,'Recepción / Almacén','+507 6996-6627','Gabriel Ruiz',false,'zcrm_4870033') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C034','Hospital Nicolás A. Solano · La Chorrera','OESTE','Salud Hospital Regional De La Chorrera (Nicolas Solano), Avenida Mariano Rivera, Residencial Vista Mar, La Chorrera, Panamá Oeste, 1015, Pan',8.865506,-79.766762,'automatica','08:00','12:00',30,'Recepción / Almacén','+507 6846-8353','Sofía Lam',false,'zcrm_4870034') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C035','Pío Pío · Arraiján','OESTE','Pío Pío, Carretera Panamericana, Residencial Vista Alegre, Nuevo Arraiján, Arraiján, Panamá Oeste, Panamá',8.927707,-79.726716,'automatica',null,null,10,'Recepción / Almacén','+507 6394-2199','Gabriel Ruiz',false,'zcrm_4870035') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into clientes(codigo,nombre,zona_codigo,direccion,lat,lng,geo_estado,ventana_inicio,ventana_fin,tiempo_servicio_min,contacto,telefono,ejecutivo,credito_bloqueado,zoho_account_id) values ('C036','Do It Center · La Chorrera','OESTE','Do It Center, Boulevard Costa Verde, La Chorrera, Panamá Oeste, 1015, Panamá',8.894628,-79.751574,'automatica',null,null,15,'Recepción / Almacén','+507 6220-9387','Sofía Lam',false,'zcrm_4870036') on conflict (codigo) do update set nombre=excluded.nombre,zona_codigo=excluded.zona_codigo,direccion=excluded.direccion,lat=excluded.lat,lng=excluded.lng,geo_estado=excluded.geo_estado,ventana_inicio=excluded.ventana_inicio,ventana_fin=excluded.ventana_fin,tiempo_servicio_min=excluded.tiempo_servicio_min,contacto=excluded.contacto,telefono=excluded.telefono,ejecutivo=excluded.ejecutivo,credito_bloqueado=excluded.credito_bloqueado,zoho_account_id=excluded.zoho_account_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1001','Detergente líquido multiusos 5 L','Limpieza',8.3,5.3,0.0062,4,false,'A-01','7450000000000','zinv_910000') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1002','Cloro concentrado 3.8 L','Limpieza',3.1,4.1,0.0045,6,false,'A-02','7450000007919','zinv_910001') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1003','Papel higiénico jumbo x12 rollos','Papel',9.9,6.0,0.09,1,false,'B-04','7450000015838','zinv_910002') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1004','Toalla de manos interfoliada x20 paq.','Papel',6.5,3.2,0.048,1,false,'B-05','7450000023757','zinv_910003') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1005','Jabón líquido para manos 1 gal x4','Higiene',14.0,9.5,0.021,1,false,'A-07','7450000031676','zinv_910004') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1006','Desinfectante hospitalario 1 gal x4','Higiene',18.9,16.0,0.018,1,false,'A-09','7450000039595','zinv_910005') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1007','Bolsas de basura 55 gal x100','Descartables',5.6,4.5,0.015,1,false,'C-02','7450000047514','zinv_910006') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1008','Vasos plásticos 16 oz x1000','Descartables',9.0,6.8,0.062,1,false,'C-06','7450000055433','zinv_910007') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1009','Servilletas x5000','Papel',7.9,7.2,0.053,1,false,'B-08','7450000063352','zinv_910008') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1010','Dispensador de jabón manual','Dispensadores',4.0,1.4,0.009,1,true,'D-01','7450000071271','zinv_910009') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1011','Alcohol en gel 70 % 1 gal x4','Higiene',19.8,15.5,0.017,1,false,'A-11','7450000079190','zinv_910010') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1012','Guantes de nitrilo x1000','Descartables',12.2,5.0,0.028,1,false,'D-03','7450000087109','zinv_910011') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1013','Dispensador de papel toalla','Dispensadores',6.5,2.1,0.014,1,true,'D-02','7450000095028','zinv_910012') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1014','Ambientador aerosol x12','Higiene',11.4,4.8,0.011,1,false,'A-14','7450000102947','zinv_910013') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1015','Limpiador de pisos 1 gal x4','Limpieza',13.6,16.4,0.018,1,false,'A-05','7450000110866','zinv_910014') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into articulos(sku,nombre,categoria,precio,peso_kg,volumen_m3,unidades_por_caja,fragil,ubicacion,codigo_barras,zoho_item_id) values ('SKU-1016','Papel higiénico doméstico x48','Papel',16.8,7.0,0.105,1,false,'B-06','7450000118785','zinv_910015') on conflict (sku) do update set nombre=excluded.nombre,categoria=excluded.categoria,precio=excluded.precio,peso_kg=excluded.peso_kg,volumen_m3=excluded.volumen_m3,unidades_por_caja=excluded.unidades_por_caja,fragil=excluded.fragil,ubicacion=excluded.ubicacion,codigo_barras=excluded.codigo_barras,zoho_item_id=excluded.zoho_item_id;
insert into vehiculos(placa,nombre,tipo,cap_valor,cap_peso_kg,cap_volumen_m3,cap_cajas,cap_posiciones,km_por_litro,panapass_tag,conductor,ayudante,color,costo_km,odometro_km,activo) values ('PA-1042','Panel 1','panel',2500,1200,8.0,220,8,9.5,'PP-88211','Luis Herrera','Rubén Díaz','#2563EB',0.42,48212,true) on conflict (placa) do update set nombre=excluded.nombre,tipo=excluded.tipo,cap_valor=excluded.cap_valor,cap_peso_kg=excluded.cap_peso_kg,cap_volumen_m3=excluded.cap_volumen_m3,cap_cajas=excluded.cap_cajas,cap_posiciones=excluded.cap_posiciones,km_por_litro=excluded.km_por_litro,panapass_tag=excluded.panapass_tag,conductor=excluded.conductor,ayudante=excluded.ayudante,color=excluded.color,costo_km=excluded.costo_km,odometro_km=excluded.odometro_km,activo=excluded.activo;
insert into vehiculos(placa,nombre,tipo,cap_valor,cap_peso_kg,cap_volumen_m3,cap_cajas,cap_posiciones,km_por_litro,panapass_tag,conductor,ayudante,color,costo_km,odometro_km,activo) values ('PA-1187','Panel 2','panel',2500,1200,8.0,220,8,9.2,'PP-88212','Carlos Pinzón','Kevin Soto','#7C3AED',0.42,51312,true) on conflict (placa) do update set nombre=excluded.nombre,tipo=excluded.tipo,cap_valor=excluded.cap_valor,cap_peso_kg=excluded.cap_peso_kg,cap_volumen_m3=excluded.cap_volumen_m3,cap_cajas=excluded.cap_cajas,cap_posiciones=excluded.cap_posiciones,km_por_litro=excluded.km_por_litro,panapass_tag=excluded.panapass_tag,conductor=excluded.conductor,ayudante=excluded.ayudante,color=excluded.color,costo_km=excluded.costo_km,odometro_km=excluded.odometro_km,activo=excluded.activo;
insert into vehiculos(placa,nombre,tipo,cap_valor,cap_peso_kg,cap_volumen_m3,cap_cajas,cap_posiciones,km_por_litro,panapass_tag,conductor,ayudante,color,costo_km,odometro_km,activo) values ('CL-3301','Camión liviano 1','camion_liviano',2500,3000,18.0,450,20,6.8,'PP-88213','José Batista',null,'#0D9488',0.61,54412,true) on conflict (placa) do update set nombre=excluded.nombre,tipo=excluded.tipo,cap_valor=excluded.cap_valor,cap_peso_kg=excluded.cap_peso_kg,cap_volumen_m3=excluded.cap_volumen_m3,cap_cajas=excluded.cap_cajas,cap_posiciones=excluded.cap_posiciones,km_por_litro=excluded.km_por_litro,panapass_tag=excluded.panapass_tag,conductor=excluded.conductor,ayudante=excluded.ayudante,color=excluded.color,costo_km=excluded.costo_km,odometro_km=excluded.odometro_km,activo=excluded.activo;
insert into vehiculos(placa,nombre,tipo,cap_valor,cap_peso_kg,cap_volumen_m3,cap_cajas,cap_posiciones,km_por_litro,panapass_tag,conductor,ayudante,color,costo_km,odometro_km,activo) values ('CM-4410','Camión mediano 1','camion_mediano',2500,5000,30.0,700,30,4.9,'PP-88214','Ana Morales',null,'#D97706',0.85,57512,true) on conflict (placa) do update set nombre=excluded.nombre,tipo=excluded.tipo,cap_valor=excluded.cap_valor,cap_peso_kg=excluded.cap_peso_kg,cap_volumen_m3=excluded.cap_volumen_m3,cap_cajas=excluded.cap_cajas,cap_posiciones=excluded.cap_posiciones,km_por_litro=excluded.km_por_litro,panapass_tag=excluded.panapass_tag,conductor=excluded.conductor,ayudante=excluded.ayudante,color=excluded.color,costo_km=excluded.costo_km,odometro_km=excluded.odometro_km,activo=excluded.activo;
insert into personas(nombre,rol,pin) values ('Luis Herrera','conductor','1234') on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Carlos Pinzón','conductor','1234') on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('José Batista','conductor','1234') on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Ana Morales','conductor','1234') on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Rubén Díaz','ayudante',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Kevin Soto','ayudante',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Marta Rojas','bodega',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Diego Castillo','bodega',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Patricia Vega','planificador',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Gabriel Ruiz','ejecutivo',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Sofía Lam','ejecutivo',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Roberto Domínguez','gerencia',null) on conflict (nombre,rol) do nothing;
insert into personas(nombre,rol,pin) values ('Admin DGP','admin',null) on conflict (nombre,rol) do nothing;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('monto_minimo','{"valor": 40}'::jsonb,'Monto mínimo por entrega (B/.). Admite sumar facturas del mismo cliente en la misma ruta.','excepcion','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('cap_valor','{"valor": 2500, "al_alcanzar": "autorizar"}'::jsonb,'Capacidad monetaria por vehículo/ruta (B/.).','autorizar','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('ventana_tolerancia','{"minutos": 15}'::jsonb,'Tolerancia sobre la ventana horaria del cliente.','alerta','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('almuerzo','{"duracion_min": 45, "desde": "12:00", "hasta": "13:30"}'::jsonb,'Parada de almuerzo del equipo.','alerta','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('checkin_radio','{"metros": 150}'::jsonb,'Distancia máxima al cliente para aceptar el check-in sin alerta.','alerta','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('desviacion_consumo','{"pct": 15}'::jsonb,'Desviación de consumo de combustible que dispara mantenimiento.','alerta','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('escalamiento_excepcion','{"horas": 2}'::jsonb,'Horas sin atender una excepción antes de escalar a gerencia.','alerta','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('velocidad_media_kmh','{"valor": 24}'::jsonb,'Velocidad media urbana para ETA cuando OSRM no responde.','alerta','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into reglas(clave,valor,descripcion,accion,actualizado_por) values ('hora_salida','{"valor": "07:00"}'::jsonb,'Hora de salida de bodega.','alerta','seed') on conflict (clave) do update set valor=excluded.valor,descripcion=excluded.descripcion;
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5201','INV-7300',id,current_date,3,429.8,313.0,1.356,62,'pendiente_validar','zso_552000' from clientes where codigo='C001';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5202','INV-7301',id,current_date,3,149.8,96.0,1.22,18,'pendiente_validar','zso_552001' from clientes where codigo='C002';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5203','INV-7302',id,current_date,3,186.0,128.6,0.216,12,'pendiente_validar','zso_552002' from clientes where codigo='C003';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5204','INV-7303',id,current_date,3,201.0,102.4,1.394,28,'pendiente_validar','zso_552003' from clientes where codigo='C004';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5205','INV-7304',id,current_date,3,508.6,363.4,0.628,34,'pendiente_validar','zso_552004' from clientes where codigo='C005';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5206','INV-7305',id,current_date,3,343.2,251.0,0.414,20,'pendiente_validar','zso_552005' from clientes where codigo='C006';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5207','INV-7306',id,current_date,3,265.4,161.6,1.911,31,'pendiente_validar','zso_552006' from clientes where codigo='C007';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5208','INV-7307',id,current_date,3,55.6,39.2,0.0848,8,'pendiente_validar','zso_552007' from clientes where codigo='C008';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5209','INV-7308',id,current_date,3,209.4,170.6,1.122,24,'pendiente_validar','zso_552008' from clientes where codigo='C009';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5210','INV-7309',id,current_date,3,24.8,21.2,0.168,3,'pendiente_validar','zso_552009' from clientes where codigo='C010';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5211','INV-7310',id,current_date,3,166.2,127.0,0.849,22,'pendiente_validar','zso_552010' from clientes where codigo='C011';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5212','INV-7311',id,current_date,3,373.8,297.2,1.168,38,'pendiente_validar','zso_552011' from clientes where codigo='C012';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5213','INV-7312',id,current_date,3,599.2,368.2,2.4572,70,'pendiente_validar','zso_552012' from clientes where codigo='C013';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5214','INV-7313',id,current_date,3,936.0,560.0,4.091,100,'pendiente_validar','zso_552013' from clientes where codigo='C014';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5215','INV-7314',id,current_date,3,82.4,47.0,0.202,10,'pendiente_validar','zso_552014' from clientes where codigo='C015';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5216','INV-7315',id,current_date,3,209.4,187.4,0.29,24,'pendiente_validar','zso_552015' from clientes where codigo='C016';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5217','INV-7316',id,current_date,3,678.6,399.2,3.052,70,'pendiente_validar','zso_552016' from clientes where codigo='C017';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5218','INV-7317',id,current_date,3,89.6,55.3,0.441,9,'pendiente_validar','zso_552017' from clientes where codigo='C018';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5219','INV-7318',id,current_date,3,51.8,41.6,0.354,6,'pendiente_validar','zso_552018' from clientes where codigo='C019';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5220','INV-7319',id,current_date,3,68.6,55.1,0.399,9,'pendiente_validar','zso_552019' from clientes where codigo='C020';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5221','INV-7320',id,current_date,3,332.0,203.4,2.526,42,'pendiente_validar','zso_552020' from clientes where codigo='C021';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5222','INV-7321',id,current_date,3,46.1,39.6,0.219,7,'pendiente_validar','zso_552021' from clientes where codigo='C022';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5223','INV-7322',id,current_date,3,283.2,187.6,1.888,32,'pendiente_validar','zso_552022' from clientes where codigo='C023';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5224','INV-7323',id,current_date,3,642.8,370.8,2.8292,68,'pendiente_validar','zso_552023' from clientes where codigo='C024';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5225','INV-7324',id,current_date,3,222.2,160.2,1.548,28,'pendiente_validar','zso_552024' from clientes where codigo='C025';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5226','INV-7325',id,current_date,3,485.2,269.2,2.2464,48,'pendiente_validar','zso_552025' from clientes where codigo='C026';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5227','INV-7326',id,current_date,3,63.6,39.4,0.088,8,'pendiente_validar','zso_552026' from clientes where codigo='C027';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5228','INV-7327',id,current_date,3,132.2,78.8,0.2392,16,'pendiente_validar','zso_552027' from clientes where codigo='C028';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5229','INV-7328',id,current_date,3,687.2,401.0,2.884,74,'pendiente_validar','zso_552028' from clientes where codigo='C029';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5230','INV-7329',id,current_date,3,186.8,103.2,1.5,24,'pendiente_validar','zso_552029' from clientes where codigo='C030';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5231','INV-7330',id,current_date,3,501.8,279.8,2.2588,50,'pendiente_validar','zso_552030' from clientes where codigo='C031';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5232','INV-7331',id,current_date,3,55.6,36.6,0.07,6,'pendiente_validar','zso_552031' from clientes where codigo='C032';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5233','INV-7332',id,current_date,3,82.4,47.0,0.202,10,'pendiente_validar','zso_552032' from clientes where codigo='C033';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5234','INV-7333',id,current_date,3,462.0,330.0,1.168,30,'pendiente_validar','zso_552033' from clientes where codigo='C034';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5235','INV-7334',id,current_date,3,16.8,13.5,0.045,3,'pendiente_validar','zso_552034' from clientes where codigo='C035';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5236','INV-7335',id,current_date,3,27.0,20.4,0.186,3,'pendiente_validar','zso_552035' from clientes where codigo='C035';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5237','INV-7336',id,current_date,3,60.4,54.0,0.0608,6,'pendiente_validar','zso_552036' from clientes where codigo='C036';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5238','INV-7337',id,current_date,3,794.0,524.0,6.21,100,'pendiente_validar','zso_552037' from clientes where codigo='C014';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5239','INV-7338',id,current_date,3,539.2,358.0,0.676,44,'pendiente_validar','zso_552038' from clientes where codigo='C001';
insert into pedidos(numero_so,numero_factura,cliente_id,fecha,prioridad,valor,peso_kg,volumen_m3,cajas,estado,zoho_salesorder_id) select 'SO-5240','INV-7339',id,current_date,3,375.0,218.4,3.276,42,'pendiente_validar','zso_552039' from clientes where codigo='C025';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',30,8.3 from pedidos where numero_so='SO-5201';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',20,3.1 from pedidos where numero_so='SO-5201';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',12,9.9 from pedidos where numero_so='SO-5201';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',8,9.9 from pedidos where numero_so='SO-5202';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',6,6.5 from pedidos where numero_so='SO-5202';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',4,7.9 from pedidos where numero_so='SO-5202';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1005',6,14.0 from pedidos where numero_so='SO-5203';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1011',4,19.8 from pedidos where numero_so='SO-5203';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1014',2,11.4 from pedidos where numero_so='SO-5203';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',10,9.9 from pedidos where numero_so='SO-5204';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',8,6.5 from pedidos where numero_so='SO-5204';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1010',6,4.0 from pedidos where numero_so='SO-5204';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1013',4,6.5 from pedidos where numero_so='SO-5204';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1006',10,18.9 from pedidos where numero_so='SO-5205';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1011',10,19.8 from pedidos where numero_so='SO-5205';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1012',8,12.2 from pedidos where numero_so='SO-5205';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1010',6,4.0 from pedidos where numero_so='SO-5205';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1006',8,18.9 from pedidos where numero_so='SO-5206';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1011',6,19.8 from pedidos where numero_so='SO-5206';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1012',6,12.2 from pedidos where numero_so='SO-5206';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',12,9.9 from pedidos where numero_so='SO-5207';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',10,6.5 from pedidos where numero_so='SO-5207';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',6,7.9 from pedidos where numero_so='SO-5207';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1014',3,11.4 from pedidos where numero_so='SO-5207';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',4,8.3 from pedidos where numero_so='SO-5208';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',4,5.6 from pedidos where numero_so='SO-5208';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',10,5.6 from pedidos where numero_so='SO-5209';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',10,9.9 from pedidos where numero_so='SO-5209';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1015',4,13.6 from pedidos where numero_so='SO-5209';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',2,7.9 from pedidos where numero_so='SO-5210';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1008',1,9.0 from pedidos where numero_so='SO-5210';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',10,3.1 from pedidos where numero_so='SO-5211';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',8,9.9 from pedidos where numero_so='SO-5211';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1005',4,14.0 from pedidos where numero_so='SO-5211';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',20,8.3 from pedidos where numero_so='SO-5212';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1015',8,13.6 from pedidos where numero_so='SO-5212';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',10,9.9 from pedidos where numero_so='SO-5212';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1016',20,16.8 from pedidos where numero_so='SO-5213';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',24,3.1 from pedidos where numero_so='SO-5213';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',16,8.3 from pedidos where numero_so='SO-5213';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',10,5.6 from pedidos where numero_so='SO-5213';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1016',30,16.8 from pedidos where numero_so='SO-5214';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',30,3.1 from pedidos where numero_so='SO-5214';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',30,8.3 from pedidos where numero_so='SO-5214';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1008',10,9.0 from pedidos where numero_so='SO-5214';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',6,5.6 from pedidos where numero_so='SO-5215';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1012',4,12.2 from pedidos where numero_so='SO-5215';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',10,8.3 from pedidos where numero_so='SO-5216';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1015',6,13.6 from pedidos where numero_so='SO-5216';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',8,5.6 from pedidos where numero_so='SO-5216';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1016',24,16.8 from pedidos where numero_so='SO-5217';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',20,3.1 from pedidos where numero_so='SO-5217';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',20,8.3 from pedidos where numero_so='SO-5217';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',6,7.9 from pedidos where numero_so='SO-5217';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',4,9.9 from pedidos where numero_so='SO-5218';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1005',3,14.0 from pedidos where numero_so='SO-5218';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1010',2,4.0 from pedidos where numero_so='SO-5218';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1008',4,9.0 from pedidos where numero_so='SO-5219';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',2,7.9 from pedidos where numero_so='SO-5219';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',3,5.6 from pedidos where numero_so='SO-5220';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1008',4,9.0 from pedidos where numero_so='SO-5220';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',2,7.9 from pedidos where numero_so='SO-5220';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',20,9.9 from pedidos where numero_so='SO-5221';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',12,6.5 from pedidos where numero_so='SO-5221';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',10,5.6 from pedidos where numero_so='SO-5221';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',4,5.6 from pedidos where numero_so='SO-5222';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',3,7.9 from pedidos where numero_so='SO-5222';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',10,9.9 from pedidos where numero_so='SO-5223';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',10,6.5 from pedidos where numero_so='SO-5223';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',8,7.9 from pedidos where numero_so='SO-5223';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1005',4,14.0 from pedidos where numero_so='SO-5223';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1016',24,16.8 from pedidos where numero_so='SO-5224';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',20,3.1 from pedidos where numero_so='SO-5224';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',16,8.3 from pedidos where numero_so='SO-5224';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',8,5.6 from pedidos where numero_so='SO-5224';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',12,9.9 from pedidos where numero_so='SO-5225';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',10,5.6 from pedidos where numero_so='SO-5225';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',6,7.9 from pedidos where numero_so='SO-5225';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1016',20,16.8 from pedidos where numero_so='SO-5226';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',16,3.1 from pedidos where numero_so='SO-5226';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',12,8.3 from pedidos where numero_so='SO-5226';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1010',6,4.0 from pedidos where numero_so='SO-5227';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1011',2,19.8 from pedidos where numero_so='SO-5227';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',6,5.6 from pedidos where numero_so='SO-5228';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1012',4,12.2 from pedidos where numero_so='SO-5228';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',6,8.3 from pedidos where numero_so='SO-5228';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1016',24,16.8 from pedidos where numero_so='SO-5229';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',20,3.1 from pedidos where numero_so='SO-5229';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',20,8.3 from pedidos where numero_so='SO-5229';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',10,5.6 from pedidos where numero_so='SO-5229';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',12,9.9 from pedidos where numero_so='SO-5230';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',8,6.5 from pedidos where numero_so='SO-5230';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1010',4,4.0 from pedidos where numero_so='SO-5230';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1016',20,16.8 from pedidos where numero_so='SO-5231';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1002',16,3.1 from pedidos where numero_so='SO-5231';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',14,8.3 from pedidos where numero_so='SO-5231';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1010',4,4.0 from pedidos where numero_so='SO-5232';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1011',2,19.8 from pedidos where numero_so='SO-5232';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',6,5.6 from pedidos where numero_so='SO-5233';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1012',4,12.2 from pedidos where numero_so='SO-5233';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1006',8,18.9 from pedidos where numero_so='SO-5234';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1011',8,19.8 from pedidos where numero_so='SO-5234';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1012',6,12.2 from pedidos where numero_so='SO-5234';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',8,9.9 from pedidos where numero_so='SO-5234';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1007',3,5.6 from pedidos where numero_so='SO-5235';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1008',3,9.0 from pedidos where numero_so='SO-5236';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',4,8.3 from pedidos where numero_so='SO-5237';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1015',2,13.6 from pedidos where numero_so='SO-5237';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',40,6.5 from pedidos where numero_so='SO-5238';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1009',30,7.9 from pedidos where numero_so='SO-5238';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',30,9.9 from pedidos where numero_so='SO-5238';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1001',20,8.3 from pedidos where numero_so='SO-5239';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1006',12,18.9 from pedidos where numero_so='SO-5239';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1012',12,12.2 from pedidos where numero_so='SO-5239';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1003',30,9.9 from pedidos where numero_so='SO-5240';
insert into pedido_lineas(pedido_id,sku,cantidad_cajas,precio) select id,'SKU-1004',12,6.5 from pedidos where numero_so='SO-5240';
insert into auditoria(entidad,accion,detalle,actor,automatico) values ('sistema','seed','Datos semilla cargados: maestros y pedidos del día','SQL Editor',true);
