import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
const out=path.resolve('docs/validacion-2026-10-10/evidencias');fs.mkdirSync(out,{recursive:true});
const results=[];
async function test(name,fn){try{await fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.message});}}
const assert=(c,m)=>{if(!c)throw Error(m);};
const app=fs.readFileSync('public/js/app.js','utf8');const inc=fs.readFileSync('public/js/incentivos.js','utf8');
await test('Sintaxis JS propio y módulos de pruebas',()=>{const files=fs.readdirSync('public/js').filter(f=>f.endsWith('.js')).map(f=>'public/js/'+f).concat(['public/sw.js',...fs.readdirSync('tests/e2e').filter(f=>f.endsWith('.mjs')).map(f=>'tests/e2e/'+f)]);for(const f of files)execFileSync(process.execPath,['--check',f]);assert(files.length===16,'cambió inventario');});
const ctx=vm.createContext({});vm.runInContext(app.split('\n').filter(l=>l.startsWith('function cabe(')||l.startsWith('function totalesDe(')).join('\n')+'\nthis.cabe=cabe;this.totalesDe=totalesDe;',ctx);
await test('Capacidad: límite exacto y exceso cajas/peso/volumen',()=>{const v={cap_cajas:120,cap_peso_kg:1000,cap_volumen_m3:5},r={cajas:119,peso_kg:999,volumen_m3:4.9};assert(Object.values(ctx.cabe(r,v,{cajas:1,peso_kg:1,volumen_m3:.1})).every(Boolean),'límite exacto rechazado');assert(!ctx.cabe(r,v,{cajas:2,peso_kg:1.01,volumen_m3:.11}).cajas,'exceso aceptado');assert(!ctx.cabe(r,v,{cajas:2,peso_kg:1.01,volumen_m3:.11}).peso,'peso excedido');assert(!ctx.cabe(r,v,{cajas:2,peso_kg:1.01,volumen_m3:.11}).vol,'volumen excedido');});
await test('Totales independientes de dos pedidos',()=>{const got=ctx.totalesDe([{valor:10.25,peso_kg:2,volumen_m3:.2,cajas:3},{valor:20.5,peso_kg:4,volumen_m3:.3,cajas:5}]);assert(JSON.stringify(got)===JSON.stringify({valor:30.75,peso_kg:6,volumen_m3:.5,cajas:8}),'totales incorrectos');});
const ci=vm.createContext({});vm.runInContext(inc.split('\n').filter(l=>l.startsWith('function semanaISO(')||l.startsWith('const cumpleInd =')||l.startsWith('const bonoDe =')).join('\n')+'\nthis.semanaISO=semanaISO;this.cumpleInd=cumpleInd;this.bonoDe=bonoDe;',ci);
await test('Semana ISO cruza año correctamente',()=>{assert(ci.semanaISO('2021-01-01')==='2020-S53','semana 53 incorrecta');assert(ci.semanaISO('2021-01-04')==='2021-S01','semana 1 incorrecta');});
await test('Bonos: umbrales, valor sin dato y hora',()=>{const cfg={tramos:[{desde:80,bono:20},{desde:100,bono:40}]};for(const [p,b] of [[79.99,0],[80,20],[99.99,20],[100,40]])assert(ci.bonoDe(cfg,p)===b,'bono incorrecto');assert(ci.cumpleInd('>=',null,0)===null,'sin dato sumó puntos');assert(ci.cumpleInd('<','07:59','08:00')===true,'hora límite incorrecta');});
const validar=app.slice(app.indexOf('async function validar()'),app.indexOf('async function promesaPago'));
async function eligibility(client,orders){const updates=[];const S={pedidos:orders.map((p,i)=>({id:String(i),numero_so:'QA'+i,numero_factura:'F'+i,cliente_id:'cli',estado:'pendiente_validar',valor:100,...p}))};const c=vm.createContext({S,exige:()=>true,R:()=>({valor:40}),cli:()=>({codigo:'QA',nombre:'QA',ejecutivo:'QA',lat:8.9,geo_estado:'validada',...client}),fmt:String,DB:{update:async(t,m,u)=>updates.push(u),remove:async()=>{},alerta:async()=>{},audit:async()=>{}},toast:()=>{},loadAll:async()=>{},render:()=>{}});vm.runInContext(validar+'\nthis.run=validar;',c);await c.run();return updates;}
await test('Elegibilidad: mínimo y complemento de facturas',async()=>{const a=await eligibility({},[{valor:39.99}]);assert(a[0].estado==='en_excepcion','bajo mínimo elegible');const b=await eligibility({},[{valor:20},{valor:20}]);assert(b.every(x=>x.estado==='elegible'&&x.grupo==='QA'),'complemento incorrecto');});
await test('Elegibilidad: promesa de pago no omite dirección dudosa',async()=>{const a=await eligibility({credito_bloqueado:true,geo_estado:'dudosa',lat:null},[{promesa_pago:{ejecutivo:'QA',fecha:'2026-10-10'}}]);assert(a[0].estado==='en_excepcion','promesa convirtió en elegible pedido sin coordenadas');});
await test('Elegibilidad: promesa de pago no omite monto mínimo',async()=>{const a=await eligibility({credito_bloqueado:true},[{valor:1,promesa_pago:{ejecutivo:'QA',fecha:'2026-10-10'}}]);assert(a[0].estado==='en_excepcion','promesa convirtió pedido de B/.1 en elegible');});
await test('Fecha operativa Panamá en medianoche UTC',()=>{const c=vm.createContext({Date:class extends Date{constructor(...a){super(...(a.length?a:['2026-10-10T02:00:00Z']));}}});vm.runInContext(app.split('\n').find(l=>l.startsWith('const hoy ='))+'\nthis.hoy=hoy;',c);assert(c.hoy()==='2026-10-09','hoy devuelve '+c.hoy()+' aunque en Panamá es 9-oct 21:00');});
const seed=JSON.parse(fs.readFileSync('data/seed.json','utf8'));
await test('Integridad JSON: claves únicas y referencias',()=>{for(const [t,k]of[['clientes','codigo'],['articulos','sku'],['pedidos','numero_so'],['vehiculos','placa']])assert(new Set(seed[t].map(x=>x[k])).size===seed[t].length,'duplicado '+t);const cli=new Set(seed.clientes.map(x=>x.codigo)),ped=new Set(seed.pedidos.map(x=>x.numero_so)),arts=new Set(seed.articulos.map(x=>x.sku));assert(seed.pedidos.every(x=>cli.has(x.cliente_codigo)),'cliente huérfano');assert(seed.pedido_lineas.every(x=>ped.has(x.numero_so)&&arts.has(x.sku)),'línea huérfana');});
await test('Totales semilla corresponden a líneas',()=>{const errors=[];const arts=Object.fromEntries(seed.articulos.map(x=>[x.sku,x]));for(const p of seed.pedidos){const ls=seed.pedido_lineas.filter(x=>x.numero_so===p.numero_so);const totals=ls.reduce((a,l)=>({cajas:a.cajas+l.cantidad_cajas,peso:a.peso+arts[l.sku].peso_kg*l.cantidad_cajas,vol:a.vol+arts[l.sku].volumen_m3*l.cantidad_cajas}),{cajas:0,peso:0,vol:0});if(p.cajas!==totals.cajas||Math.abs(p.peso_kg-totals.peso)>.011||Math.abs(p.volumen_m3-totals.vol)>.00011)errors.push({so:p.numero_so,stored:{cajas:p.cajas,peso:p.peso_kg,vol:p.volumen_m3},calculated:totals});}fs.writeFileSync(path.join(out,'seed-totals.json'),JSON.stringify(errors,null,2));assert(!errors.length,errors.length+' pedidos tienen totales inconsistentes');});
fs.writeFileSync(path.join(out,'code-data.json'),JSON.stringify({total:results.length,failed:results.filter(x=>!x.ok).length,results},null,2));for(const r of results)console.log((r.ok?'PASS ':'FAIL ')+r.name+(r.error?' — '+r.error:''));process.exitCode=results.some(x=>!x.ok)?1:0;
