import pg from 'pg';import fs from 'node:fs';import {spawnSync} from 'node:child_process';import path from 'node:path';
if(process.env.DGP_QA_ISOLATED!=='1'||process.env.PGPORT!=='55439')throw Error('QA cluster required');
const out=path.resolve('docs/validacion-2026-10-10/evidencias');const c=new pg.Client({database:'dgp_test'});await c.connect();const results=[];const q=(s,v)=>c.query(s,v);
async function test(name,fn){try{await fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.message});await q('ROLLBACK');}}
const assert=(c,m)=>{if(!c)throw Error(m);};
try{
 await test('Runner propaga fallo SQL y bloquea conexión fuera de QA',async()=>{const fail=spawnSync(process.execPath,['tests/qa/pg-cli.mjs','-d','dgp_test','-c','select QA_ERROR_DELIBERADO'],{encoding:'utf8'});const unsafe=spawnSync(process.execPath,['tests/qa/pg-cli.mjs','-c','select 1'],{encoding:'utf8',env:{...process.env,DGP_QA_ISOLATED:'0'}});assert(fail.status!==0&&unsafe.status!==0,'runner ocultó error');});
 await q("insert into rutas(codigo,conductor,estado) values('T-LUIS','Luis Herrera','publicada')");
 await q("delete from auth.users where email like 'qa-%@qa.local'");
 const roles=(await q('select codigo from roles order by orden')).rows;const tables=(await q("select tablename from pg_tables where schemaname='public' order by tablename")).rows;const matrix=[];
 for(const{codigo}of roles){const email='qa-'+codigo+'@qa.local';const {rows}=codigo==='conductor'?await q("select id from perfiles where email='cond@test.dgp'"):await q("insert into auth.users(email,raw_app_meta_data) values($1,$2) returning id",[email,{rol:codigo,activo:codigo!=='sin_rol',nombre:codigo}]);const id=rows[0].id;
  for(const{tablename}of tables){await q('BEGIN');await q("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:id,role:'authenticated'})]);await q('SET LOCAL ROLE authenticated');try{const r=await q(`select count(*)::int n from "${tablename}"`);matrix.push({role:codigo,table:tablename,read:true,rows:r.rows[0].n});}catch(e){matrix.push({role:codigo,table:tablename,read:false,error:e.code});}finally{await q('ROLLBACK');}}
 }
 fs.writeFileSync(path.join(out,'role-read-matrix.json'),JSON.stringify(matrix,null,2));
 await test('Anon no puede leer ninguna tabla pública',async()=>{for(const{tablename}of tables){await q('BEGIN');await q('SET LOCAL ROLE anon');let denied=false;try{await q(`select * from "${tablename}" limit 1`);}catch{denied=true;}await q('ROLLBACK');assert(denied,'anon leyó '+tablename);}});
 await test('Conductor no puede liberar su ruta por API de datos',async()=>{await q('BEGIN');await q("select set_config('request.jwt.claims',(select json_build_object('sub',id,'role','authenticated')::text from perfiles where email='cond@test.dgp'),true)");await q('SET LOCAL ROLE authenticated');assert((await q("select count(*)::int n from rutas where codigo='T-LUIS'")).rows[0].n===1,'fixture ruta ausente');let r=null,rechazo=null;await q('SAVEPOINT s');try{r=await q("update rutas set estado='liberada' where codigo='T-LUIS' returning codigo");}catch(e){rechazo=e.code;await q('ROLLBACK TO SAVEPOINT s');}await q('ROLLBACK');assert(rechazo==='42501'||(r&&r.rowCount===0),'conductor puede establecer liberada directamente');});
 // Regresiones añadidas con la corrección (SEG-01/05): mismo actor real, mismas claims
 const comoConductor=async(sqlText)=>{await q('BEGIN');await q("select set_config('request.jwt.claims',(select json_build_object('sub',id,'role','authenticated')::text from perfiles where email='cond@test.dgp'),true)");await q('SET LOCAL ROLE authenticated');let r=null,code=null;await q('SAVEPOINT s');try{r=await q(sqlText);}catch(e){code=e.code;await q('ROLLBACK TO SAVEPOINT s');}await q('ROLLBACK');return {rows:r?r.rowCount:0,code};};
 await test('Conductor sí puede iniciar su ruta liberada (transición legítima)',async()=>{await q("update rutas set estado='liberada' where codigo='T-LUIS'");const r=await comoConductor("update rutas set estado='en_ruta', salida_at=now(), odometro_salida=1000 where codigo='T-LUIS'");await q("update rutas set estado='publicada' where codigo='T-LUIS'");assert(r.rows===1&&!r.code,'transición legítima bloqueada: '+JSON.stringify(r));});
 await test('Conductor no puede cambiar vehículo/fecha de su ruta',async()=>{const r=await comoConductor("update rutas set fecha=fecha+1 where codigo='T-LUIS'");assert(r.code==='42501'||r.rows===0,'cambió columnas de planificación: '+JSON.stringify(r));});
 await test('Conductor no puede cambiar valor de un pedido de su ruta',async()=>{const pid=(await q("insert into pedidos(numero_so,cliente_id,fecha,valor,cajas,peso_kg,volumen_m3,estado,ruta_id) values('QA-G1',(select id from clientes limit 1),current_date,100,1,1,.01,'planificado',(select id from rutas where codigo='T-LUIS')) returning id")).rows[0].id;const r=await comoConductor(`update pedidos set valor=1 where id='${pid}'`);const ok=await comoConductor(`update pedidos set estado='entregado' where id='${pid}'`);await q(`delete from pedidos where id='${pid}'`);assert(r.code==='42501'||r.rows===0,'conductor cambió valor: '+JSON.stringify(r));assert(ok.rows===1&&!ok.code,'conductor no pudo marcar entregado: '+JSON.stringify(ok));});
 await test('Conductor no puede modificar paquetes (firmas, Zoho, estado)',async()=>{const r=await comoConductor("update paquetes set estado='registrado' where ruta_id=(select id from rutas where conductor='Luis Herrera' order by codigo limit 1)");assert(r.code==='42501'||r.rows===0,'conductor modificó paquetes: '+JSON.stringify(r));});
 await test('Odómetro de llegada menor que salida se rechaza',async()=>{await q('BEGIN');let code=null;await q('SAVEPOINT s');try{await q("update rutas set odometro_salida=5000, odometro_llegada=4000 where codigo='T-LUIS'");}catch(e){code=e.code;}await q('ROLLBACK');assert(code==='23514','base aceptó odómetro regresivo');});
 await test('Ruta no acepta estado arbitrario',async()=>{await q('BEGIN');let rejected=false;try{await q("update rutas set estado='QA_ESTADO_IMPOSIBLE' where codigo='T-LUIS'");}catch{rejected=true;}await q('ROLLBACK');assert(rejected,'base acepta estado arbitrario');});
 const policies=(await q('select schemaname,tablename,policyname,roles,cmd,qual,with_check from pg_policies order by tablename,policyname')).rows;fs.writeFileSync(path.join(out,'policies.json'),JSON.stringify(policies,null,2));
 await q("insert into pedidos(numero_so,cliente_id,fecha,valor,cajas,peso_kg,volumen_m3,estado) select 'QA-SQL-'||g,(select id from clientes limit 1),current_date,100,1,1,.01,'elegible' from generate_series(1,25000) g");
 await q("insert into eventos(ruta_id,tipo,detalle) select (select id from rutas where codigo='T-LUIS'),'qa_load',jsonb_build_object('i',g) from generate_series(1,100000) g");
 await q('ANALYZE');const plans=[];for(const s of["select * from pedidos where fecha>=current_date or estado in ('elegible','pendiente_validar') order by numero_so limit 1000","select * from eventos where ruta_id=(select id from rutas where codigo='T-LUIS') order by created_at desc limit 1500"]){await q('BEGIN');await q("select set_config('request.jwt.claims',(select json_build_object('sub',id,'role','authenticated')::text from perfiles where email='plan@test.dgp'),true)");await q('SET LOCAL ROLE authenticated');const r=await q('EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) '+s);plans.push({sql:s,plan:r.rows[0]['QUERY PLAN']});await q('ROLLBACK');}fs.writeFileSync(path.join(out,'sql-plans.json'),JSON.stringify(plans,null,2));
 console.log('Matriz:',roles.length,'roles ×',tables.length,'tablas;',matrix.length,'lecturas evaluadas. Planes sobre 25.000 pedidos/100.000 eventos.');
}finally{await c.end();fs.writeFileSync(path.join(out,'sql-audit.json'),JSON.stringify({total:results.length,failed:results.filter(x=>!x.ok).length,results},null,2));}
for(const r of results)console.log((r.ok?'PASS ':'FAIL ')+r.name+(r.error?' — '+r.error:''));process.exitCode=results.some(r=>!r.ok)?1:0;
